### ISSUE TITLE
[SP2019]Find long term carpet storage solution

### ISSUE THREAD

**Issue by jcwilliamson** [sourcebots/tasks#36] opened 2019-05-13 20:29 UTC

**Comment by Adimote** [comment] 2019-05-18 14:38
Does the carpet not fit in the carpet holder on the top of the new cupboard?

**Comment by trickeydan** [comment] 2019-05-18 17:36
> Does the carpet not fit in the carpet holder on the top of the new cupboard?

The issue is unfortunately more complicated than that. The carpet does fit on top of it, but apparently somebody else wants that space now.

I have set Reena on the case.

**Comment by jcwilliamson** [comment] 2019-05-18 17:45
Reena did ask me about the potential of using tiles. I told her that we don't think it's viable, and she seemed to agree, so it'll probably get sorted.

**Comment by trickeydan** [comment] 2019-05-18 17:55
> the potential of using tiles. 

No, not happening.

**Comment by jcwilliamson** [comment] 2019-05-18 18:31
I told Reena the same. Apparently someone in ECS was insisting on it.

**Comment by trickeydan** [comment] 2019-05-18 19:00
Well they can pay for people to place to tiles to an appropriate standard because we don't have the resources. It also means that we can't use the cinema on the Monday which will not help with the course ratings

**Comment by jcwilliamson** [comment] 2019-05-18 19:04
I'm seeing Reena on Monday, if you want, I can discuss this one with her in person.

**Comment by trickeydan** [comment] 2019-06-19 15:32
I believe this ticket can be closed as the plan is to purchase the amount of carpet we need every year after this one.

SR have a carpet roll dangerously placed on the new cupboard but that isn't a SRO or SourceBots problem at this time.

**Comment by trickeydan** [comment] 2019-07-29 19:10
We're binning it.

**Closed as completed by trickeydan** 2019-07-29 19:10 UTC
Labels: Logistics
