### ISSUE TITLE
Ensure SR purchases arena materials

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#147] opened 2019-07-22 19:25 UTC
Probably at the same time as #8

**Comment by trickeydan** [comment] 2019-07-27 23:13
@RealOrangeOne Are you alright to talk to the trustees about this?

**Comment by RealOrangeOne** [comment] 2019-07-28 09:54
I'm happy to handle the trustee comms, but I need an itemized list of exactly what we need from them (something which i'm not owning)

**Comment by Tyler-Ward** [comment] 2019-07-29 18:45
https://docs.google.com/spreadsheets/d/1uDQTWzklu0lDSMTtkIVEPOFIhDJw13x80aKt6NLL_mA/edit#gid=524286065
Is a list of what we have

**Comment by Tyler-Ward** [comment] 2019-07-29 18:47
I believe we will need 10*2m lengths of 70mm by 20mm planks

**Comment by RealOrangeOne** [comment] 2019-07-29 20:14
A prelim email has been sent to the trustees, staging we need 10 planks, and asking whether they're still ok to provide the wood, and then we'll provide a delivery address.

The email has sro@soton and Tyler CC'd in.

2m battens are logistically annoying (they're too large for me to drive down), so will need to be delivered somewhere in Southampton, ideally the uni. 

@Tyler-Ward is SUSU able to accept / store this kind of shaped delivery? I'm assuming yes being a university, but best to be sure!

**Comment by RealOrangeOne** [comment] 2019-07-29 21:36
The trustees have approved the wood order.

The closest I can find is https://www.wickes.co.uk/Wickes-Sawn-Kiln-Dried-C16-Timber---45-x-70-x-2400-mm/p/167112

If someone else approves the above link, I'll send it to the trustees for ordering (assuming they plan to order it)

**Comment by RealOrangeOne** [comment] 2019-08-02 19:58
@trickeydan recommended Totten Timber, which would save on delivery times.

I've enquired for a quote for 12m of https://www.tottontimber.com/product/sawn-softwoods_sawn-timbers/sawn-pressure-treated, which looks to fit what we need.

**Comment by RealOrangeOne** [comment] 2019-08-03 08:36
We have received a quote for the above order of ~£15. 

Once someone else confirms this order is fine, I'll try and arrange getting it to campus. Unfortunately these battens are too large to fit in my car!

**Comment by RealOrangeOne** [comment] 2019-08-05 20:18
This is somewhat blocked on #150.

Once we've concluded we need the wood, we can either order it and get it delivered (+£10) (depending on when we realise this), or take some cars down and collect it (what we need is available in store with 0 lead time).

If it's decided the wood isn't needed for this event, it can be ordered as normal and sent to the university. By that time, there's far less urgency.

It's already been agreed that I can purchase the wood, and send an invoice to SR.

**Comment by RealOrangeOne** [comment] 2019-08-09 19:00
The arena has been designed such that it's unlikely this is needed.

Therefore we can defer this to after smallpeice

**Comment by RealOrangeOne** [comment] 2019-08-18 16:12
Because of the logicstics likely required to receive the required order, this will need some liaising with someone in Southampton to ensure it can be delivered, moved and stored in the cupboard.

Not sure if it's worth me staying assigned to the ticket, but i'll leave it as-is for now. I can't make any more progress until there's a delivery plan, though.

**Comment by kierdavis** [comment] 2019-08-19 18:44
I don't think this is time-critical now since the earliest this would be needed would be April (or August if SR can confirm a non-SUSU venue for the SR2020 competition); therefore I think this can wait until term starts when we'll have more than a couple of volunteers around to cart things around and repack the cupboard.

**Comment by tpoomlmly** [comment] 2023-12-06 20:30
> or August if SR can confirm a non-SUSU venue for the SR2020 competition

yeah we confirmed a non-SUSU venue alright

**Closed as completed** 2023-12-06 20:30 UTC
Labels: MUST
