### ISSUE TITLE
[SP2019]Worksheets for Python Labs

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#143] opened 2019-07-13 19:34 UTC
Given https://github.com/sourcebots/tasks/issues/103#issuecomment-511142183, do we need worksheets?

_Originally posted by @RealOrangeOne in https://github.com/sourcebots/tasks/issues/92#issuecomment-511142317_

**Comment by kierdavis** [comment] 2019-07-14 17:37
I think previously we've just asked them to work through Whirlwind Tour and Codecademy. Do we need anything more than that?

**Comment by kierdavis** [comment] 2019-07-14 17:41
Hang on, what's the difference between this issue and #103?

**Comment by RealOrangeOne** [comment] 2019-07-15 07:34
Also, why is there a separate issue tracking _whether_ we need worksheets? Seeing as #92 is done, surely this is too?

**Comment by trickeydan** [comment] 2019-07-15 21:22
Determined that we do. See #103

**Comment by Adimote** [comment] 2019-07-22 18:33
I'll close this as it's basically a duplicate of #103

**Closed as completed by Adimote** 2019-07-22 18:33 UTC
