### ISSUE TITLE
[SP2019]Get prize mugs from joyce

### ISSUE THREAD

**Issue by Tyler-Ward** [sourcebots/tasks#142] opened 2019-07-13 16:03 UTC
we need 20 prize mugs from joyce

**Comment by JennyLouise** [comment] 2019-07-15 12:26
Have emailed Joyce and Reena about merchandise, as posted in issue #19 
Dan's emailed Joyce too, reiterating what I'd already asked for, with the addition of mugs too.
Joyce says she thinks she has 20 mugs for us, I'll confirm with her closer to the time and organise picking all the merchandise up, including mugs.
Can CC people into those emails if it'll help avoid cross posting again.

Duplicate of #19

**Closed as completed by JennyLouise** 2019-07-15 12:26 UTC
Labels: SHOULD
