### ISSUE TITLE
[SP2019]Create Smallpeice Google Calendar

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/tasks#57] opened 2019-05-21 16:47 UTC
It would be good to create a Google calendar of the Smallpeice calendar (see #110 for the calendar PDF)

**Comment by trickeydan** [comment] 2019-05-31 14:31
Son is going to do this

**Comment by joe9599** [comment] 2019-07-13 11:19
I believe this is a repeat of #110

**Comment by Adimote** [comment] 2019-07-19 21:59
I think this task describes transcribing it to a google calendar

**Comment by kierdavis** [comment] 2019-07-26 20:55
Has this been done? I vaguely remember hearing something about work being done on it in slack recently.

EDIT: yep, @jcwilliamson did this last week.

Calendar link: https://calendar.google.com/calendar?cid=aG5yMzF2NnB0aW9xbWk5ZW10MmVvZTY2bWtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Relevant slack conversation: https://sourcebots.slack.com/archives/CD93VALGL/p1563573760014000

Might be good to get a second pair of eyes to double check it matches the schedule, but I guess we can consider this otherwise done.

**Comment by jcwilliamson** [comment] 2019-07-26 21:18
@kierdavis sorry, that was my bad, I should have updated this issue.

**Comment by trickeydan** [comment] 2019-07-28 08:18
I have checked and it looks correct.

**Comment by kierdavis** [comment] 2019-07-29 11:47
The schedule (#110) has since been updated so this could do with another review.

**Comment by kierdavis** [comment] 2019-07-29 12:09
* [ ] Monday 10:25: intro talk (consisting of Housekeeping, Smallpeice welcome address, ECS welcome address, and How To Build Your Robot) is now all in 46/2003
* [ ] Tuesday 8:55: "walk to 58/1007" should now be "walk to 46/2003"
* [ ] Tuesday 9:00: academic talk is 46/2003 specifically
* [ ] Tuesday 13:00: electronics workshop is in 59/2213
* [ ] Tuesday 16:30: programming workshop is in 59/L3 labs
* [ ] Wednesday 8:50: "walk to lecture theature" should now be "walk to 46/2003"
* [ ] Wednesday 9:00: academic talk is now in 46/2003
* [ ] Wednesday 10:00: break is now in 53/4025
* [ ] Wednesday 12:30: tours now end and lunch now starts at 12:00 instead of 12:30
* [ ] Thursday 8:50: "assemble and walk to mountbatten" should now be "assemble and walk to 46/2003"
* [ ] Thursday 9:00: academic talk is now in 46/2003

Looks like I don't have write access to the calendar. @jcwilliamson since you created it please could you either make these changes or grant me write access?

**Comment by Adimote** [comment] 2019-08-05 23:52
I've updated the calendar to match the latest schedule. I'll close this for now. Please open if there's a 4th draft or a confirmed final schedule

**Closed as completed by Adimote** 2019-08-05 23:52 UTC
Labels: SHOULD
