### ISSUE TITLE
[SP2019]Plan the intro talk (what Smallpeice call 'How to build your robot')

### ISSUE THREAD

**Issue by Adimote** [sourcebots/tasks#96] opened 2019-07-08 18:40 UTC
SourceBots has an hour presentation to the competitors. This is what the Smallpeice schedule calls the "How to build your robot" presentation.

We have an hour for this, which we're going to break down into:
- [ ] How to build your robot (#144)
- [ ] Rules presentation (#131)
- [ ] ...

**Comment by RealOrangeOne** [comment] 2019-07-13 18:02
I'm happy to take this if no one else wants to. 

Alternatively, i'm also happy to tag-team it!

**Comment by RealOrangeOne** [comment] 2019-07-28 21:07
This is actually a duplicate of #144 and #131 

SourceBots don't handle the overall presentation, we simply define the rules (#131) and instructions on how to build a robot (#144)

**Comment by PeterJCLaw** [comment] 2019-08-05 18:48
Reopening as this does need planning as a whole, even if the the content is broken into the sub-tasks.

**Comment by RealOrangeOne** [comment] 2019-08-11 22:21
There is now a plan:

- How to build your robot (#144) will be handled by @andybusse
- Rules presentation (#131) will be handled by me.

**Closed as completed by RealOrangeOne** 2019-08-11 22:21 UTC
Labels: MUST
